### ISSUE TITLE
Error after Windower 4 update

### ISSUE THREAD

**Issue by xammy0** [Tylas11/XivParty#10]
I am receiving the error "Char update: ID not found" over and over ever since Windower 4 updated today. The addon seems to work otherwise and this appears to be an issue parsing a packet? Thanks for all your hard work!

**Comment by bahamut44** [comment]
I'm replying to state I am having the same issue with "Char update: ID not found". Using the Oct 3 2021 updated files.

**Comment by bahamut44** [comment]
In the config menu, under Windows and Log, the "filter" for Calls for Help turns this on/off. so it might be trying to grab packet info for calls for help?

**Comment by Tylas11** [comment]
It seems the char update packet changed and now also contains the master levels. Windower pushed a fix related to the packet a few hours ago, can you confirm that the issue is still there? 

Also a bit more context might help as I cannot reproduce the problem. Does this happen solo (with trusts) or only in party? Does zoning or reloading the addon fix it? Etc...

Btw, the log messages are posted in the "call for help" color, that's why you can filter them in the config menu.

**Comment by xammy0** [comment]
The issue is occurring on the private server LimitBreak:  https://www.limitbreakffxi.com/

The issue occurs while solo or in a group, it happens instantly upon logging in, several times, and upon changing zones, or casting a spell or using an ability.

**Comment by Tylas11** [comment]
Arent private servers all still in the 75 era? They will still use the packet without mastery levels so that might be causing the problem. Actually I'm surprised the addon works at all.
The error message itself isnt really necessary, so I'll push a quick fix just disabling it. If the addon is working otherwise, this should be good enough.

**Comment by Tylas11** [comment]
I pushed an update, download the files directly, there is no release package.
Note however, that hiding the error will not fix the actual error, which is that character update packages will be ignored when the error happens. I use this packet to update job information on party members, so that feature might be broken.

**Comment by xammy0** [comment]
Yes, we are in 75 ToAU era. The update works as expected and resolves the issue. I haven't been able to test whether the job information feature is broken or not but I will let you know if so just for reference. The addon actually doesn't work initially on the server until you change the main font to something else. Other than that I haven't had any other issues with it that I have noticed. Thanks for your help and for the addon!

**Comment by rhaba** [comment]
Issue still occurs. Fresh install of Windows, fresh install of Wings (Private server), Fresh Windower install, fresh pull of XIVParty. Thanks for your work btw. I'll try disabling call for help in the interim.

**Comment by Tylas11** [comment]
There is not much I can do other than hide some of the error messages, but the actual problem will still persist. The latest Windower version updated library files which I use to read packets. The retail server sends mastery levels, I assume the 75 era private server does not. If you want this problem fixed you need to downgrade the windower/addons/libs directory contents to a commit before the mastery level stuff was introduced. And you need to block any further updates that Windower does on startup.

**Comment by rhaba** [comment]
Gotcha, I was afraid you were going to say that. The issue with blocking updates is typically they don't allow you to manage addons from the interface, and then it all becomes a manual process.

Change sucks I suppose :).

**Comment by bahamut44** [comment]
I play on Eden private server and using latest files I am no longer seeing the “char update: ID not found” error and I have turned call for help back on. I understand the issue is still present but the error is hidden. I just wanted to inform that on Eden it seems to be hidden correctly. Not sure why it would be different on Wings server. 

Appreciate all you do. This addon is amazing. Game changer for me.
